### ISSUE TITLE
"self" not being passed as arg, so stripping other args

### ISSUE THREAD

**Issue by joel-aws** [lordjabez/file-memoizer#7]
I kept getting the same cache results returned until I made the following change:

```python
    if "result_to_cache" in kwargs:
        kwargs = {k: v for k, v in kwargs.items() if k != "result_to_cache"}
    elif ignore_self:
        if args[0] == "self":
            args = args[1:]
```

It seems like `self` wasn't getting passed as an arg to `_get_cache_key`, so it was stripping the other relevant args, meaning the hash was based off of "", making the first cache hit return no matter what.

Python version: 3.8.16

**Comment by lordjabez** [comment]
@joel-aws this is fixed in the final release (v0.4.0). Because the functionality is now supported directly in `cachier` I've deprecated this wrapper as it's no longer beneficial. Cachier should be used directly from now on.
